import "./globals.css";
import type { Metadata } from "next";

import localFont from "next/font/local";
import { Header } from "@/components/Header/Header";
import { Sidebar } from "@/components/Sidebar/Sidebar";

const helveticaFont = localFont({ src: "../fonts/helvetica_regular.otf" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={helveticaFont.className}>
                <Header />
                <Sidebar />
                {children}
            </body>
        </html>
    );
}
